name: Secret Detection

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Gitleaks
        uses: docker://zricethezav/gitleaks:latest
        with:
          args: dir . --verbose --redact